// frontend/src/views/Profile.vue
<template>
  <div class="profile-page">
    <app-header :show-back="false" title="个人中心"/>

    <!-- 用户信息头部 -->
    <div class="user-header">
      <van-image
          :src="userInfo.avatar || defaultAvatar"
          class="avatar"
          fit="cover"
          round
      />
      <div class="user-info">
        <div class="username">{{ userInfo.username || '未登录' }}</div>
        <div v-if="userInfo.phone" class="phone">{{ formatPhone(userInfo.phone) }}</div>
      </div>
    </div>

    <!-- 会员信息卡片 -->
    <div v-if="userStore.isLoggedIn && membershipInfo" class="membership-card">
      <div class="membership-header">
        <div class="level-badge">{{ membershipInfo.level_name }}</div>
        <div class="points">可用积分：{{ membershipInfo.available_points }}</div>
      </div>
      <div class="membership-progress">
        <van-progress
            :percentage="pointsProgress"
            color="#ffd21e"
        />
        <div class="progress-text">再得 {{ nextLevelPoints - membershipInfo.available_points }} 积分升级</div>
      </div>
    </div>

    <!-- 订单入口 -->
    <van-cell-group class="section">
      <van-cell is-link title="我的订单" @click="$router.push('/orders')">
        <template #icon>
          <van-icon color="#1989fa" name="orders-o" size="20"/>
        </template>
      </van-cell>
      <van-cell :value="orderStats.pending" is-link title="待支付" @click="goToOrders('pending')"/>
      <van-cell :value="orderStats.preparing" is-link title="制作中" @click="goToOrders('preparing')"/>
      <van-cell :value="orderStats.completed" is-link title="待评价" @click="goToOrders('completed')"/>
    </van-cell-group>

    <!-- 资产相关 -->
    <van-cell-group class="section">
      <van-cell is-link title="优惠券" @click="$router.push('/coupons')">
        <template #icon>
          <van-icon color="#ff976a" name="coupon-o" size="20"/>
        </template>
        <template #right-icon>
          <van-tag size="mini" type="primary">{{ couponCount }}张</van-tag>
        </template>
      </van-cell>
      <van-cell is-link title="积分中心" @click="$router.push('/points')">
        <template #icon>
          <van-icon color="#ee0a24" name="gift-o" size="20"/>
        </template>
      </van-cell>
      <van-cell is-link title="我的收藏" @click="$router.push('/favorites')">
        <template #icon>
          <van-icon color="#ffd21e" name="star-o" size="20"/>
        </template>
      </van-cell>
    </van-cell-group>

    <!-- 地址管理 -->
    <van-cell-group class="section">
      <van-cell is-link title="收货地址" @click="$router.push('/address')">
        <template #icon>
          <van-icon color="#07c160" name="location-o" size="20"/>
        </template>
      </van-cell>
    </van-cell-group>

    <!-- 客服与帮助 -->
    <van-cell-group class="section">
      <van-cell is-link title="联系客服" @click="handleContact">
        <template #icon>
          <van-icon color="#1989fa" name="service-o" size="20"/>
        </template>
      </van-cell>
      <van-cell is-link title="帮助中心" @click="$router.push('/help')">
        <template #icon>
          <van-icon color="#ff976a" name="question-o" size="20"/>
        </template>
      </van-cell>
      <van-cell is-link title="关于我们" @click="handleAbout">
        <template #icon>
          <van-icon color="#576b95" name="info-o" size="20"/>
        </template>
      </van-cell>
    </van-cell-group>

    <!-- 签到按钮 -->
    <div v-if="userStore.isLoggedIn" class="signin-section">
      <van-button
          :loading="signinLoading"
          block
          round
          type="primary"
          @click="handleSignin"
      >
        每日签到
      </van-button>
    </div>

    <!-- 退出登录 -->
    <div v-if="userStore.isLoggedIn" class="logout-section">
      <van-button
          block
          plain
          round
          type="danger"
          @click="handleLogout"
      >
        退出登录
      </van-button>
    </div>

    <!-- 底部占位 -->
    <div style="height: 30px;"></div>
  </div>
</template>

<script setup>
import {ref, computed, onMounted} from 'vue'
import {useRouter} from 'vue-router'
import {showDialog, showSuccessToast, showToast} from 'vant'
import {useUserStore} from '../stores/user'
import {userApi} from '../api/user'
import AppHeader from '../components/AppHeader.vue'

const router = useRouter()
const userStore = useUserStore()

const defaultAvatar = 'https://img.yzcdn.cn/vant/user-active.png'
const signinLoading = ref(false)

const userInfo = computed(() => userStore.userInfo || {})
const membershipInfo = ref(null)
const orderStats = ref({
  pending: 0,
  preparing: 0,
  completed: 0
})
const couponCount = ref(0)

const pointsProgress = computed(() => {
  if (!membershipInfo.value) return 0
  const nextLevelPoints = membershipInfo.value.next_level_points || 1000
  return Math.min((membershipInfo.value.available_points / nextLevelPoints) * 100, 100)
})

const nextLevelPoints = computed(() => {
  return membershipInfo.value?.next_level_points || 1000
})

onMounted(async () => {
  if (userStore.isLoggedIn) {
    await loadMembershipInfo()
    await loadOrderStats()
  }
})

const loadMembershipInfo = async () => {
  try {
    const response = await userApi.getMembershipInfo()
    membershipInfo.value = response.data
  } catch (error) {
    console.error('加载会员信息失败:', error)
    // 不显示错误提示，允许用户继续使用基本功能
  }
}

const loadOrderStats = async () => {
  try {
    const response = await userApi.getOrders()
    const orders = response.data.results || response.data
    orderStats.value.pending = orders.filter(o => o.status === 'pending').length
    orderStats.value.preparing = orders.filter(o => o.status === 'preparing').length
    orderStats.value.completed = orders.filter(o => o.status === 'completed').length
  } catch (error) {
    console.error('加载订单统计失败:', error)
    // 不显示错误提示，允许用户继续使用基本功能
  }
}

const formatPhone = (phone) => {
  if (!phone) return ''
  return phone.replace(/(\d{3})\d{4}(\d{4})/, '$1****$2')
}

const goToOrders = (status) => {
  router.push({path: '/orders', query: {status}})
}

const handleSignin = async () => {
  signinLoading.value = true
  try {
    const response = await userApi.signin()
    showSuccessToast(`签到成功！获得${response.data.points_earned}积分`)
    await loadMembershipInfo()
  } catch (error) {
    if (error.response?.data?.error) {
      showToast(error.response.data.error)
    } else {
      showToast('签到失败')
    }
  } finally {
    signinLoading.value = false
  }
}

const handleLogout = () => {
  showDialog({
    title: '确认退出',
    message: '确定要退出登录吗？',
    showCancelButton: true,
  }).then(async () => {
    await userStore.logout()
    showSuccessToast('已退出登录')
    router.push('/home')
  })
}

const handleContact = () => {
  showToast('客服功能开发中')
}

const handleAbout = () => {
  showDialog({
    title: '关于 Zdrink',
    message: 'Zdrink 智慧餐饮系统\n版本：v1.0.0\n\n提供便捷的在线点餐服务',
  })
}
</script>

<style lang="scss" scoped>
@use '../styles/variables' as *;

.profile-page {
  min-height: 100vh;
  background: $background-color;

  .user-header {
    background: linear-gradient(135deg, #1989fa, #0081ff);
    padding: 30px 20px;
    display: flex;
    align-items: center;

    .avatar {
      width: 70px;
      height: 70px;
      border: 3px solid white;
      margin-right: 15px;
    }

    .user-info {
      flex: 1;

      .username {
        font-size: $font-size-lg;
        color: white;
        font-weight: bold;
        margin-bottom: 5px;
      }

      .phone {
        font-size: $font-size-sm;
        color: rgba(255, 255, 255, 0.8);
      }
    }
  }

  .membership-card {
    margin: 10px;
    background: linear-gradient(135deg, #fff8e6, #ffffff);
    border-radius: $border-radius-lg;
    padding: 15px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);

    .membership-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 10px;

      .level-badge {
        background: linear-gradient(135deg, #ffd21e, #ff976a);
        color: white;
        padding: 4px 12px;
        border-radius: 20px;
        font-size: $font-size-sm;
        font-weight: bold;
      }

      .points {
        font-size: $font-size-md;
        color: #ff976a;
        font-weight: bold;
      }
    }

    .membership-progress {
      .progress-text {
        text-align: center;
        font-size: $font-size-xs;
        color: $text-color-light;
        margin-top: 5px;
      }
    }
  }

  .section {
    margin: 10px;
    border-radius: $border-radius-lg;
    overflow: hidden;
  }

  .signin-section {
    margin: 20px 10px;

    .van-button {
      height: 44px;
    }
  }

  .logout-section {
    margin: 0 10px 20px 10px;
  }
}
</style>

// frontend/src/app/(auth)/profile/page.tsx
'use client';

import {useEffect, useState} from 'react';
import {useRouter} from 'next/navigation';
import Image from 'next/image';
import {CreditCard, FileText, Gift, Headphones, HelpCircle, Info, LogOut, MapPin, Star, User} from 'lucide-react';
import AppHeader from '@/components/AppHeader';
import {useUserStore} from '@/stores/user';
import {userApi} from '@/lib/api/user';

interface MembershipInfo {
    level_name: string;
    available_points: number;
    next_level_points: number;
}

export default function ProfilePage() {
    const router = useRouter();
    const userStore = useUserStore();

    const [membershipInfo, setMembershipInfo] = useState<MembershipInfo | null>(null);
    const [orderStats, setOrderStats] = useState({
        pending: 0,
        preparing: 0,
        completed: 0
    });
    const [couponCount, setCouponCount] = useState(0);
    const [signinLoading, setSigninLoading] = useState(false);

    const defaultAvatar = 'https://img.yzcdn.cn/vant/user-active.png';

    // 加载会员信息和订单统计
    useEffect(() => {
        if (userStore.isLoggedIn) {
            loadMembershipInfo();
            loadOrderStats();
        }
    }, [userStore.isLoggedIn]);

    const loadMembershipInfo = async () => {
        try {
            const response = await userApi.getMembershipInfo();
            setMembershipInfo(response.data);
        } catch (error) {
            console.error('加载会员信息失败:', error);
        }
    };

    const loadOrderStats = async () => {
        try {
            const response = await userApi.getOrders();
            const orders = (response.data as any).results || response.data;
            setOrderStats({
                pending: orders.filter((o: any) => o.status === 'pending').length,
                preparing: orders.filter((o: any) => o.status === 'preparing').length,
                completed: orders.filter((o: any) => o.status === 'completed').length
            });
        } catch (error) {
            console.error('加载订单统计失败:', error);
        }
    };

    const formatPhone = (phone: string) => {
        if (!phone) return '';
        return phone.replace(/(\d{3})\d{4}(\d{4})/, '$1****$2');
    };

    const handleSignin = async () => {
        setSigninLoading(true);
        try {
            const response = await userApi.signin();
            alert(`签到成功！获得${response.data.points_earned}积分`);
            await loadMembershipInfo();
        } catch (error: any) {
            alert(error.response?.data?.error || '签到失败');
        } finally {
            setSigninLoading(false);
        }
    };

    const handleLogout = () => {
        if (!confirm('确定要退出登录吗？')) {
            return;
        }

        userStore.logout();
        alert('已退出登录');
        router.push('/home');
    };

    const goToOrders = (status: string) => {
        router.push(`/order/list?status=${status}`);
    };

    const pointsProgress = membershipInfo
        ? Math.min((membershipInfo.available_points / (membershipInfo.next_level_points || 1000)) * 100, 100)
        : 0;

    const userInfo = userStore.userInfo as any || {};

    return (
        <div className="min-h-screen bg-gray-50 pb-8">
            <AppHeader title="个人中心" showBack={false}/>

            {/* 用户信息头部 */}
            <div className="bg-gradient-to-br from-blue-500 to-blue-600 p-6 flex items-center gap-4">
                <div className="w-16 h-16 rounded-full border-2 border-white overflow-hidden bg-white">
                    {userInfo.avatar ? (
                        <Image
                            src={userInfo.avatar}
                            alt={userInfo.username || '用户'}
                            width={64}
                            height={64}
                            className="object-cover w-full h-full"
                        />
                    ) : (
                        <div className="w-full h-full flex items-center justify-center text-gray-400">
                            <User className="w-8 h-8"/>
                        </div>
                    )}
                </div>
                <div className="flex-1">
                    <div className="text-xl font-bold text-white mb-1">
                        {userInfo.username || '未登录'}
                    </div>
                    {userInfo.phone && (
                        <div className="text-sm text-white/80">
                            {formatPhone(userInfo.phone)}
                        </div>
                    )}
                </div>
            </div>

            {/* 会员信息卡片 */}
            {userStore.isLoggedIn && membershipInfo && (
                <div className="bg-gradient-to-br from-yellow-50 to-white mx-3 mt-4 rounded-xl p-4 shadow-sm">
                    <div className="flex items-center justify-between mb-3">
            <span
                className="bg-gradient-to-r from-yellow-400 to-orange-400 text-white px-3 py-1 rounded-full text-sm font-bold">
              {membershipInfo.level_name}
            </span>
                        <span className="text-orange-500 font-bold text-sm">
              可用积分：{membershipInfo.available_points}
            </span>
                    </div>
                    <div className="relative pt-4">
                        <div className="h-2 bg-gray-200 rounded-full overflow-hidden">
                            <div
                                className="h-full bg-gradient-to-r from-yellow-400 to-yellow-500 rounded-full"
                                style={{width: `${pointsProgress}%`}}
                            />
                        </div>
                        <div className="text-center text-xs text-gray-500 mt-2">
                            再得 {membershipInfo.next_level_points - membershipInfo.available_points} 积分升级
                        </div>
                    </div>
                </div>
            )}

            {/* 我的订单 */}
            <div className="bg-white mx-3 mt-4 rounded-xl overflow-hidden">
                <div
                    className="p-4 border-b border-gray-100 cursor-pointer hover:bg-gray-50 flex items-center justify-between"
                    onClick={() => router.push('/order/list')}
                >
                    <div className="flex items-center gap-3">
                        <FileText className="w-5 h-5 text-blue-500"/>
                        <span className="font-medium">我的订单</span>
                    </div>
                    <ChevronRight className="w-5 h-5 text-gray-400"/>
                </div>
                <div className="grid grid-cols-3 divide-x divide-gray-100">
                    <div
                        className="p-4 cursor-pointer hover:bg-gray-50 text-center"
                        onClick={() => goToOrders('pending')}
                    >
                        <div className="text-lg font-bold text-orange-500">{orderStats.pending}</div>
                        <div className="text-sm text-gray-500 mt-1">待支付</div>
                    </div>
                    <div
                        className="p-4 cursor-pointer hover:bg-gray-50 text-center"
                        onClick={() => goToOrders('preparing')}
                    >
                        <div className="text-lg font-bold text-blue-500">{orderStats.preparing}</div>
                        <div className="text-sm text-gray-500 mt-1">制作中</div>
                    </div>
                    <div
                        className="p-4 cursor-pointer hover:bg-gray-50 text-center"
                        onClick={() => goToOrders('completed')}
                    >
                        <div className="text-lg font-bold text-green-500">{orderStats.completed}</div>
                        <div className="text-sm text-gray-500 mt-1">待评价</div>
                    </div>
                </div>
            </div>

            {/* 资产相关 */}
            <div className="bg-white mx-3 mt-4 rounded-xl overflow-hidden">
                <div className="divide-y divide-gray-100">
                    <div className="p-4 flex items-center justify-between cursor-pointer hover:bg-gray-50">
                        <div className="flex items-center gap-3">
                            <CreditCard className="w-5 h-5 text-orange-500"/>
                            <span className="font-medium">优惠券</span>
                        </div>
                        <div className="flex items-center gap-2">
              <span className="bg-blue-100 text-blue-600 px-2 py-0.5 rounded text-xs font-medium">
                {couponCount}张
              </span>
                            <ChevronRight className="w-5 h-5 text-gray-400"/>
                        </div>
                    </div>
                    <div className="p-4 flex items-center justify-between cursor-pointer hover:bg-gray-50">
                        <div className="flex items-center gap-3">
                            <Gift className="w-5 h-5 text-red-500"/>
                            <span className="font-medium">积分中心</span>
                        </div>
                        <ChevronRight className="w-5 h-5 text-gray-400"/>
                    </div>
                    <div className="p-4 flex items-center justify-between cursor-pointer hover:bg-gray-50">
                        <div className="flex items-center gap-3">
                            <Star className="w-5 h-5 text-yellow-500"/>
                            <span className="font-medium">我的收藏</span>
                        </div>
                        <ChevronRight className="w-5 h-5 text-gray-400"/>
                    </div>
                </div>
            </div>

            {/* 地址管理 */}
            <div className="bg-white mx-3 mt-4 rounded-xl overflow-hidden">
                <div
                    className="p-4 flex items-center justify-between cursor-pointer hover:bg-gray-50"
                    onClick={() => router.push('/address')}
                >
                    <div className="flex items-center gap-3">
                        <MapPin className="w-5 h-5 text-green-500"/>
                        <span className="font-medium">收货地址</span>
                    </div>
                    <ChevronRight className="w-5 h-5 text-gray-400"/>
                </div>
            </div>

            {/* 客服与帮助 */}
            <div className="bg-white mx-3 mt-4 rounded-xl overflow-hidden">
                <div className="divide-y divide-gray-100">
                    <div className="p-4 flex items-center justify-between cursor-pointer hover:bg-gray-50">
                        <div className="flex items-center gap-3">
                            <Headphones className="w-5 h-5 text-blue-500"/>
                            <span className="font-medium">联系客服</span>
                        </div>
                        <ChevronRight className="w-5 h-5 text-gray-400"/>
                    </div>
                    <div className="p-4 flex items-center justify-between cursor-pointer hover:bg-gray-50">
                        <div className="flex items-center gap-3">
                            <HelpCircle className="w-5 h-5 text-orange-500"/>
                            <span className="font-medium">帮助中心</span>
                        </div>
                        <ChevronRight className="w-5 h-5 text-gray-400"/>
                    </div>
                    <div className="p-4 flex items-center justify-between cursor-pointer hover:bg-gray-50">
                        <div className="flex items-center gap-3">
                            <Info className="w-5 h-5 text-gray-500"/>
                            <span className="font-medium">关于我们</span>
                        </div>
                        <ChevronRight className="w-5 h-5 text-gray-400"/>
                    </div>
                </div>
            </div>

            {/* 签到按钮 */}
            {userStore.isLoggedIn && (
                <div className="mx-3 mt-6">
                    <button
                        onClick={handleSignin}
                        disabled={signinLoading}
                        className="w-full py-3 bg-blue-500 text-white rounded-lg font-medium hover:bg-blue-600 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        {signinLoading ? '签到中...' : '每日签到'}
                    </button>
                </div>
            )}

            {/* 退出登录 */}
            {userStore.isLoggedIn && (
                <div className="mx-3 mt-4">
                    <button
                        onClick={handleLogout}
                        className="w-full py-3 border border-red-500 text-red-500 rounded-lg font-medium hover:bg-red-50 transition-colors flex items-center justify-center gap-2"
                    >
                        <LogOut className="w-5 h-5"/>
                        <span>退出登录</span>
                    </button>
                </div>
            )}
        </div>
    );
}

// ChevronRight 组件
function ChevronRight({className}: { className?: string }) {
    return (
        <svg
            className={className}
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
        >
            <path strokeLinecap="round" strokeLinejoin="round" d="M9 18l6-6-6-6"/>
        </svg>
    );
}
