// frontend/src/views/Shops.vue
<template>
  <div class="shops-page">
    <app-header :show-back="true" title="全部店铺"/>

    <!-- 搜索和筛选 -->
    <div class="filter-section">
      <van-search
          v-model="searchKeyword"
          placeholder="搜索店铺"
          shape="round"
          @search="handleSearch"
      />

      <div class="filter-tags">
        <van-tag
            v-for="type in shopTypes"
            :key="type.value"
            :type="selectedType === type.value ? 'primary' : 'default'"
            plain
            size="medium"
            @click="selectType(type.value)"
        >
          {{ type.label }}
        </van-tag>
      </div>
    </div>

    <!-- 店铺列表 -->
    <div class="shops-list">
      <div
          v-for="shop in shops"
          :key="shop.id"
          class="shop-item"
          @click="goToShop(shop.id)"
      >
        <van-image
            :src="getImageUrl(shop.logo)"
            class="shop-logo"
            fit="cover"
        >
          <template v-slot:error>
            <div class="image-error">
              <van-icon name="photo-fail" size="24"/>
            </div>
          </template>
        </van-image>

        <div class="shop-info">
          <div class="shop-header">
            <h3 class="shop-name">{{ shop.name }}</h3>
            <van-tag v-if="shop.is_active" size="mini" type="success">营业中</van-tag>
          </div>

          <p class="shop-description">{{ shop.description }}</p>

          <div class="shop-meta">
            <div class="meta-item">
              <van-icon name="location-o"/>
              <span>{{ shop.address || '未知地址' }}</span>
            </div>
            <div v-if="shop.rating" class="meta-item">
              <van-rate
                  v-model="shop.rating"
                  allow-half
                  color="#ffd21e"
                  readonly
                  size="12"
              />
              <span class="rating-text">{{ shop.rating }}</span>
            </div>
          </div>

          <div class="shop-features">
            <van-tag v-if="shop.allow_delivery" plain size="mini">外卖</van-tag>
            <van-tag v-if="shop.allow_pickup" plain size="mini">自取</van-tag>
            <van-tag v-if="shop.allow_dine_in" plain size="mini">堂食</van-tag>
          </div>
        </div>

        <van-icon class="arrow-icon" name="arrow"/>
      </div>
    </div>

    <!-- 空状态 -->
    <van-empty
        v-if="!loading && shops.length === 0"
        description="暂无店铺"
        image="search"
    />

    <!-- 下拉加载 -->
    <van-list
        v-model:loading="loading"
        :finished="finished"
        finished-text="没有更多了"
        @load="onLoad"
        @pulling-down="onPullingDown"
    >
      <div style="height: 50px;"></div>
    </van-list>

    <loading :loading="loading" text="加载中..."/>
  </div>
</template>

<script setup>
import {ref, onMounted} from 'vue'
import {useRouter} from 'vue-router'
import {shopApi} from '../api/shop'
import AppHeader from '../components/AppHeader.vue'
import Loading from '../components/Loading.vue'
import {getImageUrl} from '../utils'

const router = useRouter()

const searchKeyword = ref('')
const selectedType = ref('')
const loading = ref(false)
const finished = ref(false)
const shops = ref([])
const page = ref(1)

const shopTypes = ref([
  {label: '全部', value: ''},
  {label: '餐厅', value: 'restaurant'},
  {label: '咖啡厅', value: 'cafe'},
  {label: '酒吧', value: 'bar'},
  {label: '烘焙店', value: 'bakery'},
  {label: '其他', value: 'other'}
])

onMounted(() => {
  loadShops()
})

const loadShops = async () => {
  if (loading.value) return

  loading.value = true
  try {
    const params = {
      is_active: true,
      page: page.value,
      page_size: 10
    }

    if (selectedType.value) {
      params.shop_type = selectedType.value
    }

    if (searchKeyword.value) {
      params.search = searchKeyword.value
    }

    const response = await shopApi.getShops(params)
    const newShops = response.data.results || response.data

    if (page.value === 1) {
      shops.value = newShops
    } else {
      shops.value = [...shops.value, ...newShops]
    }

    finished.value = newShops.length < 10
    page.value++
  } catch (error) {
    console.error('加载店铺失败:', error)
  } finally {
    loading.value = false
  }
}

const onLoad = () => {
  loadShops()
}

const onPullingDown = () => {
  page.value = 1
  shops.value = []
  finished.value = false
  loadShops()
}

const handleSearch = () => {
  page.value = 1
  shops.value = []
  finished.value = false
  loadShops()
}

const selectType = (type) => {
  selectedType.value = type
  page.value = 1
  shops.value = []
  finished.value = false
  loadShops()
}

const goToShop = (shopId) => {
  router.push(`/shop/${shopId}`)
}
</script>

<style lang="scss" scoped>
@use '../styles/variables' as *;

.shops-page {
  min-height: 100vh;
  background: $background-color;
  padding-bottom: 20px;

  .filter-section {
    background: white;
    padding: 10px;

    .filter-tags {
      display: flex;
      gap: 8px;
      flex-wrap: wrap;
      margin-top: 10px;
    }
  }

  .shops-list {
    padding: 10px;

    .shop-item {
      background: white;
      border-radius: $border-radius-lg;
      padding: 15px;
      margin-bottom: 10px;
      display: flex;
      position: relative;

      .shop-logo {
        width: 80px;
        height: 80px;
        border-radius: $border-radius;
        margin-right: 12px;
        flex-shrink: 0;

        .image-error {
          @include flex-center;
          height: 100%;
          background: $background-color;
          color: $text-color-light;
        }
      }

      .shop-info {
        flex: 1;
        min-width: 0;

        .shop-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 8px;

          .shop-name {
            margin: 0;
            font-size: $font-size-lg;
            font-weight: bold;
            color: $text-color;
            @include multi-line-ellipsis(1);
          }
        }

        .shop-description {
          margin: 0 0 8px 0;
          font-size: $font-size-sm;
          color: $text-color-light;
          @include multi-line-ellipsis(2);
        }

        .shop-meta {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 8px;
          font-size: $font-size-xs;
          color: $text-color-light;

          .meta-item {
            display: flex;
            align-items: center;
            gap: 4px;

            .van-icon {
              font-size: 14px;
            }

            .rating-text {
              margin-left: 4px;
              color: $warning-color;
            }
          }
        }

        .shop-features {
          display: flex;
          gap: 6px;
        }
      }

      .arrow-icon {
        position: absolute;
        right: 10px;
        top: 50%;
        transform: translateY(-50%);
        color: $text-color-light;
      }
    }
  }
}
</style>

// frontend/src/app/(auth)/shops/page.tsx
'use client';

import {useEffect, useState} from 'react';
import {useRouter} from 'next/navigation';
import Image from 'next/image';
import {ChevronRight, MapPin, Search, Star} from 'lucide-react';
import AppHeader from '@/components/AppHeader';
import Loading from '@/components/Loading';
import {shopApi} from '@/lib/api/shop';
import {getImageUrl} from '@/utils';
import {Shop} from '@/types';

interface ShopType {
    label: string;
    value: string;
}

export default function ShopsPage() {
    const router = useRouter();

    const [searchKeyword, setSearchKeyword] = useState('');
    const [selectedType, setSelectedType] = useState('');
    const [loading, setLoading] = useState(false);
    const [finished, setFinished] = useState(false);
    const [shops, setShops] = useState<Shop[]>([]);
    const [page, setPage] = useState(1);

    const shopTypes: ShopType[] = [
        {label: '全部', value: ''},
        {label: '餐厅', value: 'restaurant'},
        {label: '咖啡厅', value: 'cafe'},
        {label: '酒吧', value: 'bar'},
        {label: '烘焙店', value: 'bakery'},
        {label: '其他', value: 'other'}
    ];

    // 加载店铺列表
    const loadShops = async () => {
        if (loading) return;

        setLoading(true);
        try {
            const params: any = {
                is_active: true,
                page: page,
                page_size: 10
            };

            if (selectedType) {
                params.shop_type = selectedType;
            }

            if (searchKeyword) {
                params.search = searchKeyword;
            }

            const response = await shopApi.getShops(params);
            const newShops = (response.data as any).results || response.data;

            if (page === 1) {
                setShops(newShops);
            } else {
                setShops(prev => [...prev, ...newShops]);
            }

            setFinished(newShops.length < 10);
            setPage(prev => prev + 1);
        } catch (error) {
            console.error('加载店铺失败:', error);
        } finally {
            setLoading(false);
        }
    };

    // 初始化加载
    useEffect(() => {
        loadShops();
    }, []);

    // 无限滚动加载
    useEffect(() => {
        const handleScroll = () => {
            if (loading || finished) return;

            const scrollTop = window.innerHeight + document.documentElement.scrollTop;
            const threshold = document.documentElement.offsetHeight - 200;

            if (scrollTop >= threshold) {
                loadShops();
            }
        };

        window.addEventListener('scroll', handleScroll);
        return () => window.removeEventListener('scroll', handleScroll);
    }, [loading, finished, page, selectedType, searchKeyword]);

    const handleSearch = () => {
        setPage(1);
        setShops([]);
        setFinished(false);
        loadShops();
    };

    const selectType = (type: string) => {
        setSelectedType(type);
        setPage(1);
        setShops([]);
        setFinished(false);
    };

    const goToShop = (shopId: number) => {
        router.push(`/shop/${shopId}`);
    };

    return (
        <div className="min-h-screen bg-gray-50 pb-20">
            <AppHeader showBack={true} title="全部店铺"/>

            {/* 搜索和筛选 */}
            <div className="bg-white p-3">
                <div className="relative">
                    <input
                        type="text"
                        value={searchKeyword}
                        onChange={(e) => setSearchKeyword(e.target.value)}
                        onKeyPress={(e) => e.key === 'Enter' && handleSearch()}
                        placeholder="搜索店铺"
                        className="w-full px-4 py-2 pl-10 bg-gray-100 rounded-full focus:outline-none focus:ring-2 focus:ring-blue-500"
                    />
                    <button
                        onClick={handleSearch}
                        className="absolute right-2 top-1/2 -translate-y-1/2 p-1.5 text-gray-500 hover:text-blue-500"
                    >
                        <Search className="w-5 h-5"/>
                    </button>
                </div>

                <div className="flex flex-wrap gap-2 mt-3">
                    {shopTypes.map((type) => (
                        <button
                            key={type.value}
                            onClick={() => selectType(type.value)}
                            className={`px-4 py-1.5 rounded-full text-sm transition-colors ${
                                selectedType === type.value
                                    ? 'bg-blue-500 text-white'
                                    : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                            }`}
                        >
                            {type.label}
                        </button>
                    ))}
                </div>
            </div>

            {/* 店铺列表 */}
            <div className="p-3 space-y-3">
                {shops.map((shop) => (
                    <div
                        key={shop.id}
                        onClick={() => goToShop(shop.id)}
                        className="bg-white rounded-xl p-4 cursor-pointer hover:bg-gray-50 transition-colors relative"
                    >
                        <div className="flex gap-3">
                            <div className="w-20 h-20 rounded-lg overflow-hidden flex-shrink-0 bg-gray-100 relative">
                                {shop.logo ? (
                                    <Image
                                        src={getImageUrl(shop.logo || '')}
                                        alt={shop.name}
                                        fill
                                        className="object-cover"
                                    />
                                ) : (
                                    <div
                                        className="w-full h-full flex items-center justify-center text-gray-400 text-xs">
                                        暂无图片
                                    </div>
                                )}
                            </div>

                            <div className="flex-1 min-w-0">
                                <div className="flex items-center justify-between mb-2">
                                    <h3 className="font-semibold text-base truncate">{shop.name}</h3>
                                    {shop.is_active && (
                                        <span className="px-2 py-0.5 bg-green-100 text-green-600 text-xs rounded">
                      营业中
                    </span>
                                    )}
                                </div>

                                <p className="text-sm text-gray-500 line-clamp-2 mb-2">{shop.description}</p>

                                <div className="flex items-center justify-between mb-2 text-xs text-gray-400">
                                    <div className="flex items-center gap-1">
                                        <MapPin className="w-3 h-3"/>
                                        <span>{shop.address || '未知地址'}</span>
                                    </div>
                                    {shop.rating && (
                                        <div className="flex items-center gap-1">
                                            <Star className="w-3 h-3 fill-yellow-400 text-yellow-400"/>
                                            <span className="text-yellow-600">{shop.rating}</span>
                                        </div>
                                    )}
                                </div>

                                <div className="flex gap-2">
                                    {shop.allow_delivery && (
                                        <span
                                            className="px-2 py-0.5 border border-blue-500 text-blue-500 text-xs rounded">
                      外卖
                    </span>
                                    )}
                                    {shop.allow_pickup && (
                                        <span
                                            className="px-2 py-0.5 border border-blue-500 text-blue-500 text-xs rounded">
                      自取
                    </span>
                                    )}
                                    {shop.allow_dine_in && (
                                        <span
                                            className="px-2 py-0.5 border border-blue-500 text-blue-500 text-xs rounded">
                      堂食
                    </span>
                                    )}
                                </div>
                            </div>

                            <ChevronRight className="absolute right-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400"/>
                        </div>
                    </div>
                ))}

                {/* 空状态 */}
                {!loading && shops.length === 0 && (
                    <div className="text-center py-12">
                        <Search className="w-16 h-16 mx-auto text-gray-300 mb-4"/>
                        <p className="text-gray-500">暂无店铺</p>
                    </div>
                )}

                {/* 加载提示 */}
                {loading && (
                    <div className="text-center py-4 text-gray-500">加载中...</div>
                )}

                {/* 结束提示 */}
                {finished && shops.length > 0 && (
                    <div className="text-center py-4 text-gray-400 text-sm">没有更多了</div>
                )}
            </div>

            <Loading loading={loading && shops.length === 0} text="加载中..."/>
        </div>
    );
}
