// frontend/src/views/Register.vue
<template>
  <div class="register-page">
    <app-header title="注册" />

    <div class="register-container">
      <div class="register-logo">
        <van-image src="/logo.svg" width="80" height="80" />
        <h2>注册Zdrink账号</h2>
      </div>

      <van-form @submit="handleRegister" class="register-form">
        <van-cell-group inset>
          <van-field
            v-model="form.username"
            name="username"
            label="用户名"
            placeholder="请输入用户名"
            :rules="[{ required: true, message: '请输入用户名' }]"
            left-icon="user-o"
          />
          <van-field
            v-model="form.email"
            name="email"
            label="邮箱"
            placeholder="请输入邮箱"
            :rules="[
              { required: true, message: '请输入邮箱' },
              { validator: validateEmail, message: '邮箱格式不正确' }
            ]"
            left-icon="envelop-o"
          />
          <van-field
            v-model="form.phone"
            name="phone"
            label="手机号"
            placeholder="请输入手机号"
            :rules="[
              { required: true, message: '请输入手机号' },
              { validator: validatePhone, message: '手机号格式不正确' }
            ]"
            left-icon="phone-o"
          />
          <van-field
            v-model="form.password"
            type="password"
            name="password"
            label="密码"
            placeholder="请输入密码"
            :rules="[
              { required: true, message: '请输入密码' },
              { validator: validatePassword, message: '密码至少6位' }
            ]"
            left-icon="lock-o"
          />
          <van-field
            v-model="form.password2"
            type="password"
            name="password2"
            label="确认密码"
            placeholder="请再次输入密码"
            :rules="[
              { required: true, message: '请再次输入密码' },
              { validator: validatePassword2, message: '两次密码不一致' }
            ]"
            left-icon="lock-o"
          />
        </van-cell-group>

        <div class="form-actions">
          <van-button
            round
            block
            type="primary"
            native-type="submit"
            :loading="loading"
          >
            注册
          </van-button>
        </div>
      </van-form>

      <div class="register-links">
        <router-link to="/login" class="link">已有账号？立即登录</router-link>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { showSuccessToast, showFailToast } from 'vant'
import { useUserStore } from '../stores/user'
import AppHeader from '../components/AppHeader.vue'

const router = useRouter()
const userStore = useUserStore()

const loading = ref(false)
const form = reactive({
  username: '',
  email: '',
  phone: '',
  password: '',
  password2: '',
  user_type: 'customer'
})

const validateEmail = (value) => {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  return emailRegex.test(value)
}

const validatePhone = (value) => {
  const phoneRegex = /^1[3-9]\d{9}$/
  return phoneRegex.test(value)
}

const validatePassword = (value) => {
  return value.length >= 6
}

const validatePassword2 = (value) => {
  return value === form.password
}

const handleRegister = async () => {
  loading.value = true

  try {
    await userStore.register(form)
    showSuccessToast('注册成功')

    // 自动登录
    await userStore.login({
      username: form.username,
      password: form.password
    })

    showSuccessToast('自动登录成功')
    router.push('/home')
  } catch (error) {
    console.error('注册失败:', error)
    const errorMsg = error.response?.data?.message || error.response?.data?.detail || '注册失败'
    showFailToast(errorMsg)
  } finally {
    loading.value = false
  }
}
</script>

<style scoped lang="scss">
.register-page {
  min-height: 100vh;
  background: linear-gradient(135deg, #1989fa, #0081ff);

  .register-container {
    padding: 40px 20px;

    .register-logo {
      text-align: center;
      margin-bottom: 40px;

      h2 {
        margin: 15px 0 0 0;
        color: white;
      }
    }

    .register-form {
      .van-cell-group {
        background: transparent;

        :deep(.van-cell) {
          background: rgba(255, 255, 255, 0.9);
          margin-bottom: 15px;
        }
      }

      .form-actions {
        margin: 30px 0;

        .van-button {
          height: 44px;
        }
      }
    }

    .register-links {
      text-align: center;

      .link {
        color: white;
        text-decoration: none;

        &:hover {
          text-decoration: underline;
        }
      }
    }
  }
}
</style>

// frontend/src/app/(auth)/register/page.tsx
'use client';

import {useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {useUserStore} from '@/stores/user';

export default function RegisterPage() {
    const router = useRouter();
    const register = useUserStore((state) => state.register);

    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');
    const [formData, setFormData] = useState({
        username: '',
        email: '',
        password: '',
        re_password: ''
    });

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);
        setError('');

        // 验证密码
        if (formData.password !== formData.re_password) {
            setError('两次输入的密码不一致');
            setLoading(false);
            return;
        }

        try {
            await register({
                username: formData.username,
                email: formData.email,
                password: formData.password
            });

            // 注册成功，跳转到登录页
            router.push('/login?registered=true');
        } catch (err: any) {
            console.error('注册失败:', err);
            const errorMsg = err.response?.data?.username?.[0]
                || err.response?.data?.email?.[0]
                || err.response?.data?.password?.[0]
                || err.message
                || '注册失败，请重试';
            setError(errorMsg);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div
            className="min-h-screen bg-gradient-to-br from-green-500 to-green-600 flex items-center justify-center p-4">
            <div className="w-full max-w-md">
                {/* Logo */}
                <div className="text-center mb-10">
                    <div className="inline-block">
                        <img
                            src="/logo.svg"
                            alt="Zdrink Logo"
                            className="w-20 h-20 mx-auto"
                        />
                    </div>
                    <h1 className="text-3xl font-bold text-white mt-4">Zdrink点餐</h1>
                </div>

                {/* 注册表单 */}
                <div className="bg-white rounded-lg shadow-xl p-8">
                    <h2 className="text-2xl font-semibold text-gray-800 mb-6 text-center">
                        用户注册
                    </h2>

                    {error && (
                        <div className="mb-4 p-3 bg-red-50 border border-red-200 text-red-600 rounded-lg text-sm">
                            {error}
                        </div>
                    )}

                    <form onSubmit={handleSubmit} className="space-y-4">
                        <div>
                            <label htmlFor="username" className="block text-sm font-medium text-gray-700 mb-1">
                                用户名
                            </label>
                            <input
                                id="username"
                                type="text"
                                value={formData.username}
                                onChange={(e) => setFormData({...formData, username: e.target.value})}
                                placeholder="请输入用户名"
                                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
                                required
                            />
                        </div>

                        <div>
                            <label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-1">
                                邮箱
                            </label>
                            <input
                                id="email"
                                type="email"
                                value={formData.email}
                                onChange={(e) => setFormData({...formData, email: e.target.value})}
                                placeholder="请输入邮箱"
                                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
                                required
                            />
                        </div>

                        <div>
                            <label htmlFor="password" className="block text-sm font-medium text-gray-700 mb-1">
                                密码
                            </label>
                            <input
                                id="password"
                                type="password"
                                value={formData.password}
                                onChange={(e) => setFormData({...formData, password: e.target.value})}
                                placeholder="请输入密码"
                                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
                                required
                            />
                        </div>

                        <div>
                            <label htmlFor="re_password" className="block text-sm font-medium text-gray-700 mb-1">
                                确认密码
                            </label>
                            <input
                                id="re_password"
                                type="password"
                                value={formData.re_password}
                                onChange={(e) => setFormData({...formData, re_password: e.target.value})}
                                placeholder="请再次输入密码"
                                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
                                required
                            />
                        </div>

                        <button
                            type="submit"
                            disabled={loading}
                            className={`w-full py-3 px-4 rounded-lg text-white font-medium transition-colors ${
                                loading
                                    ? 'bg-green-400 cursor-not-allowed'
                                    : 'bg-green-500 hover:bg-green-600'
                            }`}
                        >
                            {loading ? '注册中...' : '注册'}
                        </button>
                    </form>

                    {/* 链接 */}
                    <div className="mt-6 text-center">
                        <p className="text-sm text-gray-600">
                            已有账号？{' '}
                            <Link
                                href="/login"
                                className="text-green-600 hover:text-green-700 font-medium"
                            >
                                立即登录
                            </Link>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
}
