// frontend/src/views/Search.vue
<template>
  <div class="search-page">
    <app-header :show-back="true" title="搜索"/>

    <!-- 搜索栏 -->
    <div class="search-bar">
      <van-search
          v-model="keyword"
          placeholder="搜索店铺或商品"
          shape="round"
          show-action
          @cancel="handleCancel"
          @search="handleSearch"
      >
        <template #action>
          <div @click="handleSearch">搜索</div>
        </template>
      </van-search>
    </div>

    <!-- 搜索历史 -->
    <div v-if="!hasSearched && searchHistory.length > 0" class="history-section">
      <div class="section-header">
        <span>搜索历史</span>
        <van-icon name="delete-o" @click="clearHistory"/>
      </div>
      <div class="history-tags">
        <van-tag
            v-for="(item, index) in searchHistory"
            :key="index"
            plain
            size="medium"
            type="primary"
            @click="searchByHistory(item)"
        >
          {{ item }}
        </van-tag>
      </div>
    </div>

    <!-- 热门搜索 -->
    <div v-if="!hasSearched" class="hot-section">
      <div class="section-header">
        <span>热门搜索</span>
      </div>
      <div class="hot-tags">
        <van-tag
            v-for="(tag, index) in hotTags"
            :key="index"
            size="medium"
            type="primary"
            @click="searchByTag(tag)"
        >
          {{ tag }}
        </van-tag>
      </div>
    </div>

    <!-- 搜索结果 - 店铺 -->
    <div v-if="hasSearched && shops.length > 0" class="result-section">
      <div class="section-title">相关店铺</div>
      <div class="shops-list">
        <div
            v-for="shop in shops"
            :key="shop.id"
            class="shop-item"
            @click="goToShop(shop.id)"
        >
          <van-image
              :src="getImageUrl(shop.logo)"
              class="shop-logo"
              fit="cover"
          />
          <div class="shop-info">
            <h3 class="shop-name">{{ shop.name }}</h3>
            <p class="shop-desc">{{ shop.description }}</p>
            <van-tag v-if="shop.is_active" size="mini" type="success">营业中</van-tag>
          </div>
        </div>
      </div>
    </div>

    <!-- 搜索结果 - 商品 -->
    <div v-if="hasSearched && products.length > 0" class="result-section">
      <div class="section-title">相关商品</div>
      <div class="products-list">
        <product-card
            v-for="product in products"
            :key="product.id"
            :product="product"
            :show-add-button="true"
            @click="goToProduct(product.id)"
            @add-to-cart="handleAddToCart"
        />
      </div>
    </div>

    <!-- 空状态 -->
    <van-empty
        v-if="hasSearched && shops.length === 0 && products.length === 0"
        description="未找到相关内容"
        image="search"
    />

    <loading :loading="loading" text="加载中..."/>
  </div>
</template>

<script setup>
import {ref, onMounted} from 'vue'
import {useRouter, useRoute} from 'vue-router'
import {showToast, showSuccessToast} from 'vant'
import {shopApi} from '../api/shop'
import {productApi} from '../api/product'
import {useCartStore} from '../stores/cart'
import AppHeader from '../components/AppHeader.vue'
import ProductCard from '../components/ProductCard.vue'
import Loading from '../components/Loading.vue'
import {getImageUrl} from '../utils'

const router = useRouter()
const route = useRoute()
const cartStore = useCartStore()

const keyword = ref('')
const loading = ref(false)
const hasSearched = ref(false)
const searchHistory = ref([])
const shops = ref([])
const products = ref([])

const hotTags = ref([
  '奶茶',
  '咖啡',
  '蛋糕',
  '披萨',
  '汉堡',
  '果汁'
])

onMounted(() => {
  // 从 URL 获取搜索关键词
  const queryKeyword = route.query.q
  if (queryKeyword) {
    keyword.value = queryKeyword
    handleSearch()
  }
  loadHistory()
})

const loadHistory = () => {
  const history = localStorage.getItem('search_history')
  if (history) {
    searchHistory.value = JSON.parse(history)
  }
}

const saveHistory = (keyword) => {
  if (!searchHistory.value.includes(keyword)) {
    searchHistory.value.unshift(keyword)
    // 只保留最近 10 条
    searchHistory.value = searchHistory.value.slice(0, 10)
    localStorage.setItem('search_history', JSON.stringify(searchHistory.value))
  }
}

const clearHistory = () => {
  searchHistory.value = []
  localStorage.removeItem('search_history')
}

const handleSearch = async () => {
  if (!keyword.value.trim()) {
    showToast('请输入搜索内容')
    return
  }

  loading.value = true
  hasSearched.value = true

  try {
    // 保存搜索历史
    saveHistory(keyword.value)

    // 搜索店铺
    const shopResponse = await shopApi.getShops({
      search: keyword.value,
      is_active: true
    })
    shops.value = shopResponse.data.results || shopResponse.data

    // 搜索商品
    const productResponse = await productApi.getPublicProducts('', {
      search: keyword.value,
      status: 'active'
    })
    products.value = productResponse.data.results || productResponse.data
  } catch (error) {
    console.error('搜索失败:', error)
    showToast('搜索失败，请稍后重试')
  } finally {
    loading.value = false
  }
}

const handleCancel = () => {
  router.back()
}

const searchByHistory = (item) => {
  keyword.value = item
  handleSearch()
}

const searchByTag = (tag) => {
  keyword.value = tag
  handleSearch()
}

const goToShop = (shopId) => {
  router.push(`/shop/${shopId}`)
}

const goToProduct = (productId) => {
  router.push(`/product/${productId}`)
}

const handleAddToCart = async (product) => {
  try {
    await cartStore.addToCart({
      product_id: product.id,
      quantity: 1
    })
    showSuccessToast('已添加到购物车')
  } catch (error) {
    console.error('添加到购物车失败:', error)
  }
}
</script>

<style lang="scss" scoped>
@use '../styles/variables' as *;

.search-page {
  min-height: 100vh;
  background: $background-color;

  .search-bar {
    background: white;
    padding: 10px;
  }

  .history-section,
  .hot-section {
    background: white;
    padding: 15px;
    margin-bottom: 10px;

    .section-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 10px;
      font-size: $font-size-md;
      font-weight: bold;
      color: $text-color;

      .van-icon {
        font-size: 16px;
        color: $text-color-light;
      }
    }

    .history-tags,
    .hot-tags {
      display: flex;
      gap: 8px;
      flex-wrap: wrap;
    }
  }

  .result-section {
    background: white;
    padding: 15px;
    margin-bottom: 10px;

    .section-title {
      font-size: $font-size-lg;
      font-weight: bold;
      margin-bottom: 15px;
      color: $text-color;
    }

    .shops-list {
      .shop-item {
        display: flex;
        padding: 12px 0;
        border-bottom: 1px solid $border-color;

        &:last-child {
          border-bottom: none;
        }

        .shop-logo {
          width: 60px;
          height: 60px;
          border-radius: $border-radius;
          margin-right: 12px;
        }

        .shop-info {
          flex: 1;

          .shop-name {
            margin: 0 0 6px 0;
            font-size: $font-size-md;
            font-weight: bold;
            @include multi-line-ellipsis(1);
          }

          .shop-desc {
            margin: 0 0 6px 0;
            font-size: $font-size-sm;
            color: $text-color-light;
            @include multi-line-ellipsis(2);
          }
        }
      }
    }

    .products-list {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 12px;
    }
  }
}
</style>

// frontend/src/app/(auth)/search/page.tsx
'use client';

import {useEffect, useState, Suspense} from 'react';
import {useRouter, useSearchParams} from 'next/navigation';
import Image from 'next/image';
import {Search, Trash2} from 'lucide-react';
import AppHeader from '@/components/AppHeader';
import Loading from '@/components/Loading';
import ProductCard from '@/components/ProductCard';
import {shopApi} from '@/lib/api/shop';
import {productApi} from '@/lib/api/product';
import {useCartStore} from '@/stores/cart';
import {getImageUrl} from '@/utils';
import {Product, Shop} from '@/types';

export default function SearchPage() {
    return (
        <Suspense fallback={<div className="min-h-screen bg-gray-50 flex items-center justify-center">加载中...</div>}>
            <SearchContent/>
        </Suspense>
    );
}

function SearchContent() {
    const router = useRouter();
    const searchParams = useSearchParams();
    const cartStore = useCartStore();

    const [keyword, setKeyword] = useState('');
    const [loading, setLoading] = useState(false);
    const [hasSearched, setHasSearched] = useState(false);
    const [searchHistory, setSearchHistory] = useState<string[]>([]);
    const [shops, setShops] = useState<Shop[]>([]);
    const [products, setProducts] = useState<Product[]>([]);

    const hotTags = ['奶茶', '咖啡', '蛋糕', '披萨', '汉堡', '果汁'];

    // 加载搜索历史
    const loadHistory = () => {
        const history = localStorage.getItem('search_history');
        if (history) {
            setSearchHistory(JSON.parse(history));
        }
    };

    // 保存搜索历史
    const saveHistory = (keyword: string) => {
        const newHistory = [keyword, ...searchHistory.filter(h => h !== keyword)].slice(0, 10);
        setSearchHistory(newHistory);
        localStorage.setItem('search_history', JSON.stringify(newHistory));
    };

    // 清除历史
    const clearHistory = () => {
        setSearchHistory([]);
        localStorage.removeItem('search_history');
    };

    // 执行搜索
    const handleSearch = async () => {
        if (!keyword || !keyword.trim()) {
            alert('请输入搜索内容');
            return;
        }

        setLoading(true);
        setHasSearched(true);

        try {
            // 保存搜索历史
            saveHistory(keyword);

            // 搜索店铺
            const shopResponse = await shopApi.getShops({
                search: keyword,
                is_active: true
            });
            setShops((shopResponse.data as any).results || shopResponse.data);

            // 搜索商品
            const productResponse = await productApi.getPublicProducts(0, {
                search: keyword,
                page_size: 20
            });
            setProducts(((productResponse.data as any).results || productResponse.data) as Product[]);
        } catch (error) {
            console.error('搜索失败:', error);
            alert('搜索失败，请稍后重试');
        } finally {
            setLoading(false);
        }
    };

    // 从 URL 参数获取搜索关键词
    useEffect(() => {
        const queryKeyword = searchParams.get('q');
        if (queryKeyword) {
            setKeyword(queryKeyword);
            // 自动执行搜索
            setTimeout(() => {
                handleSearch();
            }, 100);
        }
        loadHistory();
    }, [searchParams]);

    const searchByHistory = (item: string) => {
        setKeyword(item);
        handleSearch();
    };

    const searchByTag = (tag: string) => {
        setKeyword(tag);
        handleSearch();
    };

    const goToShop = (shopId: number) => {
        router.push(`/shop/${shopId}`);
    };

    const goToProduct = (productId: number) => {
        router.push(`/product/${productId}`);
    };

    const handleAddToCart = async (product: Product) => {
        try {
            await cartStore.addToCart({
                product: product.id,
                quantity: 1
            });
        } catch (error) {
            console.error('添加到购物车失败:', error);
        }
    };

    return (
        <div className="min-h-screen bg-gray-50 pb-20">
            <AppHeader showBack={true} title="搜索"/>

            {/* 搜索栏 */}
            <div className="bg-white p-3">
                <div className="flex items-center gap-2">
                    <div className="flex-1 relative">
                        <input
                            type="text"
                            value={keyword}
                            onChange={(e) => setKeyword(e.target.value)}
                            onKeyPress={(e) => e.key === 'Enter' && handleSearch()}
                            placeholder="搜索店铺或商品"
                            className="w-full px-4 py-2 pl-10 bg-gray-100 rounded-full focus:outline-none focus:ring-2 focus:ring-blue-500"
                        />
                        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400"/>
                    </div>
                    <button
                        onClick={handleSearch}
                        className="px-4 py-2 bg-blue-500 text-white rounded-full hover:bg-blue-600 transition-colors"
                    >
                        搜索
                    </button>
                </div>
            </div>

            {/* 搜索历史和热门搜索 */}
            {!hasSearched && (
                <>
                    {/* 搜索历史 */}
                    {searchHistory.length > 0 && (
                        <div className="bg-white p-4 mb-3">
                            <div className="flex items-center justify-between mb-3">
                                <span className="font-semibold">搜索历史</span>
                                <button onClick={clearHistory} className="text-gray-400 hover:text-gray-600">
                                    <Trash2 className="w-5 h-5"/>
                                </button>
                            </div>
                            <div className="flex flex-wrap gap-2">
                                {searchHistory.map((item, index) => (
                                    <button
                                        key={index}
                                        onClick={() => searchByHistory(item)}
                                        className="px-3 py-1.5 bg-blue-50 text-blue-600 text-sm rounded-full hover:bg-blue-100 transition-colors"
                                    >
                                        {item}
                                    </button>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* 热门搜索 */}
                    <div className="bg-white p-4">
                        <div className="font-semibold mb-3">热门搜索</div>
                        <div className="flex flex-wrap gap-2">
                            {hotTags.map((tag, index) => (
                                <button
                                    key={index}
                                    onClick={() => searchByTag(tag)}
                                    className="px-3 py-1.5 bg-gray-100 text-gray-700 text-sm rounded-full hover:bg-gray-200 transition-colors"
                                >
                                    {tag}
                                </button>
                            ))}
                        </div>
                    </div>
                </>
            )}

            {/* 搜索结果 */}
            {hasSearched && (
                <>
                    {/* 店铺结果 */}
                    {shops.length > 0 && (
                        <div className="bg-white p-4 mb-3">
                            <div className="font-bold text-lg mb-4">相关店铺</div>
                            <div className="space-y-4">
                                {shops.map((shop) => (
                                    <div
                                        key={shop.id}
                                        onClick={() => goToShop(shop.id)}
                                        className="flex cursor-pointer hover:bg-gray-50 rounded-lg p-2 transition-colors"
                                    >
                                        <div
                                            className="w-16 h-16 rounded-lg overflow-hidden flex-shrink-0 bg-gray-100 relative">
                                            {shop.logo ? (
                                                <Image
                                                    src={getImageUrl(shop.logo || '')}
                                                    alt={shop.name}
                                                    fill
                                                    className="object-cover"
                                                />
                                            ) : (
                                                <div
                                                    className="w-full h-full flex items-center justify-center text-gray-400 text-xs">
                                                    暂无图片
                                                </div>
                                            )}
                                        </div>
                                        <div className="ml-3 flex-1">
                                            <h3 className="font-semibold text-base mb-1">{shop.name}</h3>
                                            <p className="text-sm text-gray-500 line-clamp-2 mb-2">{shop.description}</p>
                                            {shop.is_active && (
                                                <span
                                                    className="px-2 py-0.5 bg-green-100 text-green-600 text-xs rounded">
                          营业中
                        </span>
                                            )}
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* 商品结果 */}
                    {products.length > 0 && (
                        <div className="bg-white p-4">
                            <div className="font-bold text-lg mb-4">相关商品</div>
                            <div className="grid grid-cols-2 gap-3">
                                {products.map((product) => (
                                    <ProductCard
                                        key={product.id}
                                        id={product.id}
                                        name={product.name}
                                        description={product.description}
                                        price={product.price}
                                        originalPrice={product.original_price}
                                        image={product.image}
                                        isAvailable={product.is_available}
                                        onClick={() => goToProduct(product.id)}
                                        onAddToCart={() => handleAddToCart(product)}
                                    />
                                ))}
                            </div>
                        </div>
                    )}

                    {/* 空状态 */}
                    {shops.length === 0 && products.length === 0 && (
                        <div className="text-center py-12">
                            <Search className="w-16 h-16 mx-auto text-gray-300 mb-4"/>
                            <p className="text-gray-500">未找到相关内容</p>
                        </div>
                    )}
                </>
            )}

            <Loading loading={loading} text="加载中..."/>
        </div>
    );
}
