// frontend/src/views/Login.vue
<template>
  <div class="login-page">
    <app-header title="登录" />

    <div class="login-container">
      <div class="login-logo">
        <van-image src="/logo.svg" width="80" height="80" />
        <h2>Zdrink点餐</h2>
      </div>

      <van-form @submit="handleLogin" class="login-form">
        <van-cell-group inset>
          <van-field
            v-model="form.username"
            name="username"
            label="用户名"
            placeholder="请输入用户名"
            :rules="[{ required: true, message: '请输入用户名' }]"
            left-icon="user-o"
          />
          <van-field
            v-model="form.password"
            type="password"
            name="password"
            label="密码"
            placeholder="请输入密码"
            :rules="[{ required: true, message: '请输入密码' }]"
            left-icon="lock-o"
          />
        </van-cell-group>

        <div class="form-actions">
          <van-button
            round
            block
            type="primary"
            native-type="submit"
            :loading="loading"
          >
            登录
          </van-button>
        </div>
      </van-form>

      <div class="login-links">
        <router-link to="/register" class="link">立即注册</router-link>
        <span class="divider">|</span>
        <a href="#" class="link" @click.prevent="handleForgetPassword">忘记密码</a>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { showSuccessToast, showFailToast } from 'vant'
import { useUserStore } from '../stores/user'
import AppHeader from '../components/AppHeader.vue'

const router = useRouter()
const route = useRoute()
const userStore = useUserStore()

const loading = ref(false)
const form = reactive({
  username: '',
  password: ''
})

const handleLogin = async () => {
  loading.value = true

  try {
    await userStore.login(form)
    showSuccessToast('登录成功')

    // 跳转到目标页面或首页
    const redirect = route.query.redirect || '/home'
    router.push(redirect)
  } catch (error) {
    console.error('登录失败:', error)
    showFailToast('登录失败，请检查用户名和密码')
  } finally {
    loading.value = false
  }
}

const handleForgetPassword = () => {
  showFailToast('请联系管理员重置密码')
}
</script>
<style scoped lang="scss">
@use '../styles/variables' as *;
@use "sass:color";
.login-page {
  min-height: 100vh;
  background: linear-gradient(135deg, #1989fa, #0081ff);

  .login-container {
    padding: 40px 20px;

    .login-logo {
      text-align: center;
      margin-bottom: 40px;

      h2 {
        margin: 15px 0 0 0;
        color: white;
        font-size: $font-size-xl;
      }
    }

    .login-form {
      .van-cell-group {
        background: transparent;

        :deep(.van-cell) {
          background: rgba(255, 255, 255, 0.9);
          border-radius: $border-radius;
          margin-bottom: 15px;
        }
      }

      .form-actions {
        margin: 30px 0;

        .van-button {
          height: 44px;
          font-size: $font-size-lg;
        }
      }
    }

    .login-links {
      text-align: center;

      .link {
        color: white;
        text-decoration: none;
        font-size: $font-size-md;

        &:hover {
          text-decoration: underline;
        }
      }

      .divider {
        color: white;
        margin: 0 15px;
      }
    }
  }
}
</style>

// frontend/src/app/(auth)/login/page.tsx
'use client';

import {useState, Suspense} from 'react';
import {useRouter, useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {useUserStore} from '@/stores/user';

export default function LoginPage() {
    return (
        <Suspense fallback={<div
            className="min-h-screen bg-gradient-to-br from-blue-500 to-blue-600 flex items-center justify-center">
            <div className="text-white text-xl">加载中...</div>
        </div>}>
            <LoginContent/>
        </Suspense>
    );
}

function LoginContent() {
    const router = useRouter();
    const searchParams = useSearchParams();
    const login = useUserStore((state) => state.login);

    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');
    const [formData, setFormData] = useState({
        username: '',
        password: ''
    });

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);
        setError('');

        try {
            console.log('尝试登录，用户名:', formData.username);
            await login(formData);
            // 登录成功，跳转到目标页面
            const callbackUrl = searchParams.get('callbackUrl') || searchParams.get('redirect') || '/home';
            router.push(callbackUrl);
        } catch (err: any) {
            console.error('登录失败:', err);
            console.error('错误响应:', err.response);
            console.error('错误数据:', err.response?.data);

            // 尝试获取具体的错误信息
            let errorMsg = '登录失败，请检查用户名和密码';

            if (err.response?.data) {
                const errorData = err.response.data;
                // Django DRF 可能返回字段级别的错误
                if (typeof errorData === 'object') {
                    // 尝试获取 username 或 password 字段的错误
                    errorMsg = errorData.username?.[0]
                        || errorData.password?.[0]
                        || errorData.detail
                        || errorData.message
                        || JSON.stringify(errorData);
                } else if (typeof errorData === 'string') {
                    errorMsg = errorData;
                }
            } else if (err.message) {
                errorMsg = err.message;
            }

            setError(errorMsg);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="min-h-screen bg-gradient-to-br from-blue-500 to-blue-600 flex items-center justify-center p-4">
            <div className="w-full max-w-md">
                {/* Logo */}
                <div className="text-center mb-10">
                    <div className="inline-block">
                        <img
                            src="/logo.svg"
                            alt="Zdrink Logo"
                            className="w-20 h-20 mx-auto"
                        />
                    </div>
                    <h1 className="text-3xl font-bold text-white mt-4">Zdrink点餐</h1>
                </div>

                {/* 登录表单 */}
                <div className="bg-white rounded-lg shadow-xl p-8">
                    <h2 className="text-2xl font-semibold text-gray-800 mb-6 text-center">
                        用户登录
                    </h2>

                    {error && (
                        <div className="mb-4 p-3 bg-red-50 border border-red-200 text-red-600 rounded-lg text-sm">
                            {error}
                        </div>
                    )}

                    {/* 注册成功提示 */}
                    {searchParams.get('registered') && (
                        <div className="mb-4 p-3 bg-green-50 border border-green-200 text-green-600 rounded-lg text-sm">
                            注册成功，请登录
                        </div>
                    )}

                    <form onSubmit={handleSubmit} className="space-y-4">
                        <div>
                            <label htmlFor="username" className="block text-sm font-medium text-gray-700 mb-1">
                                用户名
                            </label>
                            <input
                                id="username"
                                type="text"
                                value={formData.username}
                                onChange={(e) => setFormData({...formData, username: e.target.value})}
                                placeholder="请输入用户名"
                                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                required
                            />
                        </div>

                        <div>
                            <label htmlFor="password" className="block text-sm font-medium text-gray-700 mb-1">
                                密码
                            </label>
                            <input
                                id="password"
                                type="password"
                                value={formData.password}
                                onChange={(e) => setFormData({...formData, password: e.target.value})}
                                placeholder="请输入密码"
                                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                required
                            />
                        </div>

                        <button
                            type="submit"
                            disabled={loading}
                            className={`w-full py-3 px-4 rounded-lg text-white font-medium transition-colors ${
                                loading
                                    ? 'bg-blue-400 cursor-not-allowed'
                                    : 'bg-blue-500 hover:bg-blue-600'
                            }`}
                        >
                            {loading ? '登录中...' : '登录'}
                        </button>
                    </form>

                    {/* 链接 */}
                    <div className="mt-6 text-center">
                        <div className="flex items-center justify-center space-x-4">
                            <Link
                                href="/register"
                                className="text-blue-600 hover:text-blue-700 text-sm font-medium"
                            >
                                立即注册
                            </Link>
                            <span className="text-gray-300">|</span>
                            <a
                                href="#"
                                onClick={(e) => {
                                    e.preventDefault();
                                    alert('请联系管理员重置密码');
                                }}
                                className="text-blue-600 hover:text-blue-700 text-sm font-medium"
                            >
                                忘记密码
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
