// frontend/src/app/(auth)/categories/page.tsx
'use client';

import {useEffect, useState} from 'react';
import {useRouter} from 'next/navigation';
import Image from 'next/image';
import {ChevronRight, Grid} from 'lucide-react';
import AppHeader from '@/components/AppHeader';
import Loading from '@/components/Loading';
import {productApi} from '@/lib/api/product';
import {getImageUrl} from '@/utils';
import {Category} from '@/types';

export default function CategoriesPage() {
    const router = useRouter();

    const [loading, setLoading] = useState(false);
    const [categories, setCategories] = useState<Category[]>([]);

    // 加载分类列表
    const loadCategories = async () => {
        setLoading(true);
        try {
            const response = await productApi.getCategories(0);
            setCategories((response.data as any).results || response.data);
        } catch (error) {
            console.error('加载分类失败:', error);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        loadCategories();
    }, []);

    const goToCategory = (category: Category) => {
        router.push(`/products?category_id=${category.id}&category_name=${category.name}`);
    };

    return (
        <div className="min-h-screen bg-gray-50 pb-20">
            <AppHeader showBack={true} title="全部分类"/>

            {/* 分类列表 */}
            <div className="p-3 space-y-3">
                {categories.map((category) => (
                    <div
                        key={category.id}
                        onClick={() => goToCategory(category)}
                        className="bg-white rounded-xl p-4 cursor-pointer hover:bg-gray-50 transition-colors relative flex items-center"
                    >
                        <div className="w-16 h-16 rounded-full overflow-hidden flex-shrink-0 bg-gray-100 relative mr-4">
                            {category.icon ? (
                                <Image
                                    src={getImageUrl(category.icon)}
                                    alt={category.name}
                                    fill
                                    className="object-cover"
                                />
                            ) : (
                                <div className="w-full h-full flex items-center justify-center text-gray-400">
                                    <Grid className="w-8 h-8"/>
                                </div>
                            )}
                        </div>

                        <div className="flex-1 min-w-0">
                            <h3 className="font-semibold text-base truncate mb-1">{category.name}</h3>
                            {category.description && (
                                <p className="text-sm text-gray-500 line-clamp-2 mb-1">
                                    {category.description}
                                </p>
                            )}
                            {category.product_count !== undefined && (
                                <div className="text-xs text-gray-400">
                                    {category.product_count}个商品
                                </div>
                            )}
                        </div>

                        <ChevronRight className="w-5 h-5 text-gray-400"/>
                    </div>
                ))}

                {/* 空状态 */}
                {!loading && categories.length === 0 && (
                    <div className="text-center py-12">
                        <Grid className="w-16 h-16 mx-auto text-gray-300 mb-4"/>
                        <p className="text-gray-500">暂无分类</p>
                    </div>
                )}
            </div>

            <Loading loading={loading} text="加载中..."/>
        </div>
    );
}

// frontend/src/views/Categories.vue
<template>
  <div class="categories-page">
    <app-header :show-back="true" title="全部分类"/>

    <!-- 分类列表 -->
    <div class="categories-list">
      <div
          v-for="category in categories"
          :key="category.id"
          class="category-item"
          @click="goToCategory(category)"
      >
        <van-image
            :src="getImageUrl(category.icon)"
            class="category-icon"
            fit="cover"
            round
        >
          <template v-slot:error>
            <div class="icon-error">
              <van-icon name="apps-o" size="24"/>
            </div>
          </template>
        </van-image>

        <div class="category-info">
          <h3 class="category-name">{{ category.name }}</h3>
          <p v-if="category.description" class="category-desc">
            {{ category.description }}
          </p>
          <div v-if="category.product_count !== undefined" class="category-meta">
            <span>{{ category.product_count }}个商品</span>
          </div>
        </div>

        <van-icon class="arrow-icon" name="arrow"/>
      </div>
    </div>

    <!-- 空状态 -->
    <van-empty
        v-if="!loading && categories.length === 0"
        description="暂无分类"
        image="search"
    />

    <loading :loading="loading" text="加载中..."/>
  </div>
</template>

<script setup>
import {ref, onMounted} from 'vue'
import {useRouter} from 'vue-router'
import {productApi} from '../api/product'
import AppHeader from '../components/AppHeader.vue'
import Loading from '../components/Loading.vue'
import {getImageUrl} from '../utils'

const router = useRouter()
const loading = ref(false)
const categories = ref([])

onMounted(async () => {
  await loadCategories()
})

const loadCategories = async () => {
  loading.value = true
  try {
    const response = await productApi.getCategories()
    categories.value = response.data.results || response.data
  } catch (error) {
    console.error('加载分类失败:', error)
  } finally {
    loading.value = false
  }
}

const goToCategory = (category) => {
  router.push({
    path: '/products',
    query: {
      category_id: category.id,
      category_name: category.name
    }
  })
}
</script>

<style lang="scss" scoped>
@use '../styles/variables' as *;

.categories-page {
  min-height: 100vh;
  background: $background-color;

  .categories-list {
    padding: 10px;

    .category-item {
      background: white;
      border-radius: $border-radius-lg;
      padding: 15px;
      margin-bottom: 10px;
      display: flex;
      align-items: center;
      position: relative;

      .category-icon {
        width: 60px;
        height: 60px;
        margin-right: 15px;
        flex-shrink: 0;

        .icon-error {
          @include flex-center;
          height: 100%;
          background: $background-color;
          color: $text-color-light;
        }
      }

      .category-info {
        flex: 1;
        min-width: 0;

        .category-name {
          margin: 0 0 6px 0;
          font-size: $font-size-lg;
          font-weight: bold;
          color: $text-color;
          @include multi-line-ellipsis(1);
        }

        .category-desc {
          margin: 0 0 6px 0;
          font-size: $font-size-sm;
          color: $text-color-light;
          @include multi-line-ellipsis(2);
        }

        .category-meta {
          font-size: $font-size-xs;
          color: $text-color-light;
        }
      }

      .arrow-icon {
        color: $text-color-light;
        font-size: 16px;
      }
    }
  }
}
</style>
