// frontend/src/app/(auth)/home/page.tsx
'use client';

import {useEffect, useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import Image from 'next/image';
import {Gift, Grid, HelpCircle, Home, MapPin, ShoppingCart, Ticket, User} from 'lucide-react';
import AppHeader from '@/components/AppHeader';
import Loading from '@/components/Loading';
import {useUserStore} from '@/stores/user';
import {useCartStore} from '@/stores/cart';
import {shopApi} from '@/lib/api/shop';
import {getImageUrl} from '@/utils';
import {Shop} from '@/types';

// 功能入口图标映射
const featureIcons: Record<string, any> = {
    'shop-o': MapPin,
    'coupon-o': Ticket,
    'gift-o': Gift,
    'question-o': HelpCircle
};

export default function HomePage() {
    const router = useRouter();
    const userStore = useUserStore();
    const cartStore = useCartStore();

    const [activeTab, setActiveTab] = useState('home');
    const [searchKeyword, setSearchKeyword] = useState('');
    const [loading, setLoading] = useState(false);
    const [banners] = useState([
        {id: 1, image: '/images/banner1.jpg', link: '/promotion/1'},
        {id: 2, image: '/images/banner2.jpg', link: '/promotion/2'},
        {id: 3, image: '/images/banner3.jpg', link: '/promotion/3'}
    ]);
    const [featuredShops, setFeaturedShops] = useState<Shop[]>([]);

    // 功能入口
    const features = [
        {id: 1, icon: 'shop-o', text: '附近店铺', path: '/shops'},
        {id: 2, icon: 'coupon-o', text: '优惠券', path: '/coupons'},
        {id: 3, icon: 'gift-o', text: '积分兑换', path: '/points'},
        {id: 4, icon: 'question-o', text: '使用帮助', path: '/help'}
    ];

    // 加载数据
    const loadData = async () => {
        setLoading(true);
        try {
            // 加载推荐店铺
            const shopResponse = await shopApi.getShops({is_active: true, limit: 6});
            setFeaturedShops((shopResponse.data.results || shopResponse.data) as Shop[]);
        } catch (error) {
            console.error('加载数据失败:', error);
        } finally {
            setLoading(false);
        }
    };

    // 加载购物车
    const loadCart = async () => {
        if (userStore.isLoggedIn) {
            try {
                await cartStore.getCart();
                console.log('购物车加载成功');
            } catch (error) {
                console.log('加载购物车失败:', error);
            }
        }
    };

    // 监听登录状态变化
    useEffect(() => {
        if (userStore.isLoggedIn) {
            loadCart();
        }
    }, [userStore.isLoggedIn]);

    // 初始化用户信息
    useEffect(() => {
        userStore.initUser();
    }, []);

    // 初始化加载
    useEffect(() => {
        loadData();
        loadCart();
    }, []);

    const handleSearch = () => {
        if (searchKeyword && searchKeyword.trim()) {
            router.push(`/search?q=${encodeURIComponent(searchKeyword)}`);
        }
    };

    const handleFeatureClick = (path: string) => {
        router.push(path);
    };

    const handleTabChange = (name: string) => {
        const routes: Record<string, string> = {
            home: '/home',
            category: '/categories',
            cart: '/cart',
            profile: '/profile'
        };
        if (routes[name]) {
            router.push(routes[name]);
        }
    };

    const goToShopList = () => {
        router.push('/shops');
    };

    const goToShop = (shopId: number) => {
        router.push(`/shop/${shopId}`);
    };

    const getShopTypeText = (type: string) => {
        const typeMap: Record<string, string> = {
            restaurant: '餐厅',
            cafe: '咖啡厅',
            bar: '酒吧',
            bakery: '烘焙店',
            other: '其他'
        };
        return typeMap[type] || '店铺';
    };

    return (
        <div className="min-h-screen bg-gray-50 pb-16">
            <AppHeader title="Zdrink 点餐" showBack={false} showCart={true}/>

            {/* 搜索栏 */}
            <div className="p-3 bg-white">
                <div className="relative">
                    <input
                        type="text"
                        value={searchKeyword}
                        onChange={(e) => setSearchKeyword(e.target.value)}
                        onKeyPress={(e) => e.key === 'Enter' && handleSearch()}
                        placeholder="搜索店铺或商品"
                        className="w-full px-4 py-2 pl-10 bg-gray-100 rounded-full focus:outline-none focus:ring-2 focus:ring-blue-500"
                    />
                    <svg
                        className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                    >
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                              d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
                    </svg>
                </div>
            </div>

            {/* 轮播图 */}
            {banners.length > 0 && (
                <div className="mx-3 mt-3 rounded-xl overflow-hidden">
                    <div className="relative h-32 w-full overflow-hidden">
                        {banners.map((banner, index) => (
                            <div
                                key={banner.id}
                                className={`absolute inset-0 transition-opacity duration-1000 ${
                                    index === 0 ? 'opacity-100' : 'opacity-0'
                                }`}
                            >
                                <img
                                    src={banner.image}
                                    alt={`Banner ${index + 1}`}
                                    className="w-full h-full object-cover"
                                />
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* 功能入口 */}
            <div className="mx-3 mt-3 bg-white rounded-xl p-4">
                <div className="grid grid-cols-4 gap-4">
                    {features.map((feature) => {
                        const IconComponent = featureIcons[feature.icon] || MapPin;
                        return (
                            <button
                                key={feature.id}
                                onClick={() => handleFeatureClick(feature.path)}
                                className="flex flex-col items-center justify-center space-y-2 hover:bg-gray-50 rounded-lg transition-colors p-2"
                            >
                                <IconComponent className="w-8 h-8 text-blue-500"/>
                                <span className="text-sm text-gray-700">{feature.text}</span>
                            </button>
                        );
                    })}
                </div>
            </div>

            {/* 推荐店铺 */}
            <div className="mx-3 mt-3 bg-white rounded-xl p-4">
                <div className="flex items-center justify-between mb-4">
                    <h2 className="text-lg font-bold">推荐店铺</h2>
                    <button
                        onClick={goToShopList}
                        className="px-3 py-1 bg-blue-500 text-white text-sm rounded-full hover:bg-blue-600 transition-colors"
                    >
                        查看更多
                    </button>
                </div>

                <div className="space-y-4">
                    {featuredShops.map((shop) => (
                        <div
                            key={shop.id}
                            onClick={() => goToShop(shop.id)}
                            className="flex cursor-pointer border-b border-gray-100 pb-4 last:border-0 last:pb-0 hover:bg-gray-50 rounded-lg p-2 transition-colors"
                        >
                            <div className="w-16 h-16 rounded-lg overflow-hidden flex-shrink-0 bg-gray-100">
                                {shop.logo ? (
                                    <Image
                                        src={getImageUrl(shop.logo || '')}
                                        alt={shop.name}
                                        width={64}
                                        height={64}
                                        className="object-cover"
                                    />
                                ) : (
                                    <div className="w-full h-full flex items-center justify-center text-gray-400">
                                        暂无图片
                                    </div>
                                )}
                            </div>
                            <div className="ml-3 flex-1">
                                <h3 className="font-semibold text-base mb-1">{shop.name}</h3>
                                <p className="text-sm text-gray-500 line-clamp-1 mb-2">{shop.description}</p>
                                <div className="flex items-center space-x-2">
                                    <span className="text-xs text-gray-400">{getShopTypeText(shop.shop_type)}</span>
                                    <span
                                        className={`text-xs px-2 py-0.5 rounded ${
                                            shop.is_active
                                                ? 'bg-green-100 text-green-600'
                                                : 'bg-gray-100 text-gray-500'
                                        }`}
                                    >
                    {shop.is_active ? '营业中' : '已打烊'}
                  </span>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>

            {/* 底部导航 */}
            <nav className="fixed bottom-0 left-0 right-0 bg-white border-t border-gray-200 safe-area-bottom md:hidden">
                <div className="flex items-center justify-around h-14">
                    <button
                        onClick={() => handleTabChange('home')}
                        className={`flex flex-col items-center justify-center space-y-1 ${
                            activeTab === 'home' ? 'text-blue-500' : 'text-gray-500'
                        }`}
                    >
                        <Home className="w-6 h-6"/>
                        <span className="text-xs">首页</span>
                    </button>

                    <button
                        onClick={() => handleTabChange('category')}
                        className={`flex flex-col items-center justify-center space-y-1 ${
                            activeTab === 'category' ? 'text-blue-500' : 'text-gray-500'
                        }`}
                    >
                        <Grid className="w-6 h-6"/>
                        <span className="text-xs">分类</span>
                    </button>

                    <Link
                        href="/cart"
                        className="flex flex-col items-center justify-center space-y-1 text-gray-500 relative"
                    >
                        <div className="relative">
                            <ShoppingCart className="w-6 h-6"/>
                            {cartStore.totalQuantity > 0 && (
                                <span
                                    className="absolute -top-2 -right-2 bg-red-500 text-white text-xs w-5 h-5 flex items-center justify-center rounded-full">
                  {cartStore.totalQuantity > 99 ? '99+' : cartStore.totalQuantity}
                </span>
                            )}
                        </div>
                        <span className="text-xs">购物车</span>
                    </Link>

                    <Link
                        href="/profile"
                        className={`flex flex-col items-center justify-center space-y-1 ${
                            activeTab === 'profile' ? 'text-blue-500' : 'text-gray-500'
                        }`}
                    >
                        <User className="w-6 h-6"/>
                        <span className="text-xs">我的</span>
                    </Link>
                </div>
            </nav>

            <Loading loading={loading} text="加载中..."/>
        </div>
    );
}

// frontend/src/views/Home.vue
<template>
  <div class="home-page">
    <app-header title="Zdrink点餐" :show-back="false" :show-cart="true" />

    <!-- 搜索栏 -->
    <div class="search-section">
      <van-search
        v-model="searchKeyword"
        placeholder="搜索店铺或商品"
        shape="round"
        @search="handleSearch"
      />
    </div>

    <!-- 轮播图 -->
    <div class="banner-section" v-if="banners.length > 0">
      <van-swipe :autoplay="3000" indicator-color="white">
        <van-swipe-item v-for="banner in banners" :key="banner.id">
          <van-image :src="banner.image" fit="cover" />
        </van-swipe-item>
      </van-swipe>
    </div>

    <!-- 功能入口 -->
    <div class="feature-section">
      <van-grid :column-num="4" :border="false">
        <van-grid-item
          v-for="feature in features"
          :key="feature.id"
          :icon="feature.icon"
          :text="feature.text"
          @click="handleFeatureClick(feature)"
        />
      </van-grid>
    </div>

    <!-- 推荐店铺 -->
    <div class="shop-section">
      <div class="section-header">
        <h2 class="section-title">推荐店铺</h2>
        <van-button type="primary" size="mini" text="查看更多" @click="goToShopList" />
      </div>

      <div class="shop-list">
        <div
          v-for="shop in featuredShops"
          :key="shop.id"
          class="shop-item"
          @click="goToShop(shop.id)"
        >
          <van-image
            :src="getImageUrl(shop.logo)"
            class="shop-logo"
            fit="cover"
          />
          <div class="shop-info">
            <h3 class="shop-name">{{ shop.name }}</h3>
            <p class="shop-desc">{{ shop.description }}</p>
            <div class="shop-meta">
              <span class="shop-type">{{ getShopTypeText(shop.shop_type) }}</span>
              <span class="shop-status" :class="shop.is_active ? 'open' : 'closed'">
                {{ shop.is_active ? '营业中' : '已打烊' }}
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- 底部导航 -->
    <van-tabbar v-model="activeTab" @change="handleTabChange">
      <van-tabbar-item icon="home-o" name="home">首页</van-tabbar-item>
      <van-tabbar-item icon="apps-o" name="category">分类</van-tabbar-item>
      <van-tabbar-item icon="shopping-cart-o" name="cart" :badge="cartStore.totalQuantity">
        购物车
      </van-tabbar-item>
      <van-tabbar-item icon="user-o" name="profile">我的</van-tabbar-item>
    </van-tabbar>

    <loading :loading="loading" text="加载中..." />
  </div>
</template>

<script setup>
import {ref, onMounted, watch} from 'vue'
import { useRouter } from 'vue-router'
import { useCartStore } from '../stores/cart'
import {useUserStore} from '../stores/user'
import { shopApi } from '../api/shop'
import AppHeader from '../components/AppHeader.vue'
import Loading from '../components/Loading.vue'
import { getImageUrl } from '../utils'

const router = useRouter()
const cartStore = useCartStore()
const userStore = useUserStore()

const activeTab = ref('home')
const searchKeyword = ref('')
const loading = ref(false)
const banners = ref([])
const featuredShops = ref([])

// 功能入口
const features = ref([
  { id: 1, icon: 'shop-o', text: '附近店铺', path: '/shops' },
  { id: 2, icon: 'coupon-o', text: '优惠券', path: '/coupons' },
  { id: 3, icon: 'gift-o', text: '积分兑换', path: '/points' },
  { id: 4, icon: 'question-o', text: '使用帮助', path: '/help' }
])

const loadCart = async () => {
  if (userStore.isLoggedIn) {
    try {
      await cartStore.getCart()
      console.log('购物车加载成功')
    } catch (error) {
      console.log('加载购物车失败:', error)
    }
  }
}

onMounted(async () => {
  await loadData()
  // 立即尝试加载购物车
  await loadCart()
})

// 监听登录状态变化
watch(() => userStore.isLoggedIn, (newVal) => {
  console.log('登录状态变化:', newVal)
  if (newVal) {
    loadCart()
  }
})

const loadData = async () => {
  loading.value = true
  try {
    // 加载推荐店铺
    const shopResponse = await shopApi.getShops({ is_active: true, limit: 6 })
    featuredShops.value = shopResponse.data.results || shopResponse.data

    // 模拟轮播图数据
    banners.value = [
      { id: 1, image: '/images/banner1.jpg', link: '/promotion/1' },
      { id: 2, image: '/images/banner2.jpg', link: '/promotion/2' },
      { id: 3, image: '/images/banner3.jpg', link: '/promotion/3' }
    ]
  } catch (error) {
    console.error('加载数据失败:', error)
  } finally {
    loading.value = false
  }
}

const handleSearch = () => {
  if (searchKeyword.value.trim()) {
    router.push(`/search?q=${encodeURIComponent(searchKeyword.value)}`)
  }
}

const handleFeatureClick = (feature) => {
  router.push(feature.path)
}

const handleTabChange = (name) => {
  const routes = {
    home: '/home',
    category: '/categories',
    cart: '/cart',
    profile: '/profile'
  }
  if (routes[name]) {
    router.push(routes[name])
  }
}

const goToShopList = () => {
  router.push('/shops')
}

const goToShop = (shopId) => {
  router.push(`/shop/${shopId}`)
}

const getShopTypeText = (type) => {
  const typeMap = {
    restaurant: '餐厅',
    cafe: '咖啡厅',
    bar: '酒吧',
    bakery: '烘焙店',
    other: '其他'
  }
  return typeMap[type] || '店铺'
}
</script>

<style scoped lang="scss">
@use '../styles/variables' as *;
@use "sass:color";
.home-page {
  padding-bottom: 50px;

  .search-section {
    padding: 10px;
    background: white;
  }

  .banner-section {
    margin: 10px;
    border-radius: $border-radius-lg;
    overflow: hidden;

    .van-swipe {
      height: 120px;
    }
  }

  .feature-section {
    margin: 10px;
    background: white;
    border-radius: $border-radius-lg;

    :deep(.van-grid-item__content) {
      padding: 15px 8px;
    }
  }

  .shop-section {
    margin: 10px;
    background: white;
    border-radius: $border-radius-lg;
    padding: 15px;

    .section-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 15px;

      .section-title {
        margin: 0;
        font-size: $font-size-lg;
        font-weight: bold;
      }
    }

    .shop-list {
      .shop-item {
        display: flex;
        padding: 12px 0;
        border-bottom: 1px solid $border-color;

        &:last-child {
          border-bottom: none;
        }

        .shop-logo {
          width: 60px;
          height: 60px;
          border-radius: $border-radius;
          margin-right: 12px;
        }

        .shop-info {
          flex: 1;

          .shop-name {
            margin: 0 0 4px 0;
            font-size: $font-size-md;
            font-weight: bold;
          }

          .shop-desc {
            margin: 0 0 6px 0;
            font-size: $font-size-sm;
            color: $text-color-light;
            @include multi-line-ellipsis(1);
          }

          .shop-meta {
            display: flex;
            align-items: center;

            .shop-type {
              font-size: $font-size-xs;
              color: $text-color-light;
              margin-right: 8px;
            }

            .shop-status {
              font-size: $font-size-xs;
              padding: 2px 6px;
              border-radius: $border-radius;

              &.open {
                background: color.adjust($success-color, $lightness: 40%);
                color: $success-color;
              }

              &.closed {
                background: color.adjust($text-color-light, $lightness: 40%);
                color: $text-color-light;
              }
            }
          }
        }
      }
    }
  }
}
</style>
